global using Ambs.Reporting.DAL.Entities;
global using Ambs.Reporting.DAL.Repository.Interfaces;
global using Microsoft.EntityFrameworkCore;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Text;
global using System.Threading.Tasks;