global using Ambs.Reporting.DAL.Repository.Interfaces;
global using Ambs.Reporting.Engine.Model;
global using Ambs.Reporting.Service.Interfaces;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Ambs.Reporting.DAL.Entities;